#!/bin/bash
set -e
. /home/rvm/.rvm/scripts/rvm
rvm 2.3.3
rvm gemset use redmine-gems
cd /opt/redmine
export PASSENGER_LOCATION_CONFIGURATION_FILE=/opt/redmine/locations.ini
export CC='ccache clang'
export CXX='ccache clang++'
exec bundle "$@"
